<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Version>4.9.0</Version>
	<FileVersion>4.9.0.0</FileVersion> 
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64</Platforms>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="Sdcb.PaddleInference" Version="3.0.1" />
    <PackageReference Include="Sdcb.PaddleInference.runtime.win64.mkl" Version="3.1.0.54" />
    <PackageReference Include="Sdcb.PaddleOCR" Version="3.0.1" />
    <PackageReference Include="Sdcb.PaddleOCR.Models.Online" Version="3.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\icon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

</Project>
